export type Category = "Breakfast" | "Lunch" | "Dinner" | "Dessert" | "Snack" | "Drinks";
export type Difficulty = "Easy" | "Medium" | "Hard";

export interface Recipe {
  id: string;
  name: string;
  description: string;
  category: Category;
  difficulty: Difficulty;
  prepTime: number;
  cookTime: number;
  servings: number;
  calories: number;
  rating: number;
  emoji: string;
  tags: string[];
  ingredients: { amount: string; item: string }[];
  steps: string[];
  tips: string[];
}

export const recipes: Recipe[] = [
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    description: "Creamy smashed avocado on crispy sourdough with cherry tomatoes and a poached egg.",
    category: "Breakfast",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    calories: 320,
    rating: 4.8,
    emoji: "🥑",
    tags: ["vegetarian", "healthy", "quick"],
    ingredients: [
      { amount: "2 slices", item: "sourdough bread" },
      { amount: "2", item: "ripe avocados" },
      { amount: "1 tbsp", item: "lemon juice" },
      { amount: "½ tsp", item: "red pepper flakes" },
      { amount: "2", item: "eggs (poached)" },
      { amount: "6", item: "cherry tomatoes, halved" },
      { amount: "to taste", item: "salt and black pepper" },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "handful", item: "fresh basil leaves" },
    ],
    steps: [
      "Toast the sourdough slices until golden and crispy.",
      "Halve the avocados, remove pits, and scoop flesh into a bowl.",
      "Add lemon juice, salt, and pepper. Mash with a fork to your preferred texture.",
      "Bring a small pot of water to a gentle simmer. Add a splash of white vinegar.",
      "Crack each egg into a small cup, then gently slide into the simmering water. Poach 3–4 minutes.",
      "Spread mashed avocado generously over each toast slice.",
      "Top with cherry tomatoes, a poached egg, and red pepper flakes.",
      "Drizzle with olive oil and garnish with fresh basil. Serve immediately.",
    ],
    tips: [
      "Use very ripe avocados for the creamiest texture.",
      "Add a splash of white vinegar to the poaching water to help the egg white hold together.",
      "Season at every step for the best depth of flavor.",
    ],
  },
  {
    id: "classic-pancakes",
    name: "Fluffy Buttermilk Pancakes",
    description: "Light, airy pancakes with a golden crust, served with maple syrup and fresh berries.",
    category: "Breakfast",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 280,
    rating: 4.9,
    emoji: "🥞",
    tags: ["vegetarian", "sweet", "family-friendly"],
    ingredients: [
      { amount: "2 cups", item: "all-purpose flour" },
      { amount: "2 tbsp", item: "sugar" },
      { amount: "2 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "baking soda" },
      { amount: "½ tsp", item: "salt" },
      { amount: "2 cups", item: "buttermilk" },
      { amount: "2", item: "large eggs" },
      { amount: "3 tbsp", item: "melted butter" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "to serve", item: "maple syrup and fresh berries" },
    ],
    steps: [
      "Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.",
      "In a separate bowl, whisk buttermilk, eggs, melted butter, and vanilla.",
      "Pour the wet ingredients into the dry. Stir gently until just combined — lumps are fine!",
      "Let batter rest 5 minutes while you heat a non-stick skillet over medium heat.",
      "Lightly grease the pan. Pour ¼ cup batter per pancake.",
      "Cook until bubbles form on the surface and edges look set, about 2–3 minutes.",
      "Flip and cook another 1–2 minutes until golden brown.",
      "Serve immediately with maple syrup and fresh berries.",
    ],
    tips: [
      "Do NOT overmix the batter — lumps mean fluffier pancakes.",
      "Let the batter rest to let the baking powder activate.",
      "Keep finished pancakes warm in a 200°F oven while you cook the rest.",
    ],
  },
  {
    id: "caprese-salad",
    name: "Classic Caprese Salad",
    description: "Fresh mozzarella, ripe tomatoes, and fragrant basil with a balsamic glaze.",
    category: "Lunch",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 220,
    rating: 4.7,
    emoji: "🍅",
    tags: ["vegetarian", "Italian", "no-cook", "healthy"],
    ingredients: [
      { amount: "3 large", item: "ripe tomatoes, sliced" },
      { amount: "250g", item: "fresh mozzarella, sliced" },
      { amount: "1 bunch", item: "fresh basil leaves" },
      { amount: "3 tbsp", item: "extra virgin olive oil" },
      { amount: "2 tbsp", item: "balsamic glaze" },
      { amount: "to taste", item: "flaky sea salt and black pepper" },
    ],
    steps: [
      "Slice tomatoes and mozzarella into ¼-inch thick rounds.",
      "Arrange alternating slices of tomato, mozzarella, and basil on a large plate.",
      "Drizzle generously with extra virgin olive oil.",
      "Drizzle balsamic glaze over the top in a zigzag pattern.",
      "Season with flaky sea salt and freshly cracked black pepper.",
      "Serve immediately at room temperature.",
    ],
    tips: [
      "Use the best quality ingredients — this dish is all about quality.",
      "Room-temperature mozzarella has a creamier texture than cold.",
      "Balsamic glaze (reduced balsamic vinegar) is sweeter than regular balsamic.",
    ],
  },
  {
    id: "chicken-caesar-wrap",
    name: "Grilled Chicken Caesar Wrap",
    description: "Tender grilled chicken, crisp romaine, parmesan, and Caesar dressing in a toasted flour tortilla.",
    category: "Lunch",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    calories: 480,
    rating: 4.6,
    emoji: "🌯",
    tags: ["protein-rich", "meal-prep", "quick"],
    ingredients: [
      { amount: "2", item: "chicken breasts" },
      { amount: "2 large", item: "flour tortillas" },
      { amount: "3 cups", item: "romaine lettuce, chopped" },
      { amount: "¼ cup", item: "parmesan cheese, shaved" },
      { amount: "¼ cup", item: "Caesar dressing" },
      { amount: "1 cup", item: "croutons" },
      { amount: "1 tsp", item: "garlic powder" },
      { amount: "1 tsp", item: "Italian seasoning" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Season chicken with garlic powder, Italian seasoning, salt, and pepper.",
      "Grill or pan-sear chicken 6–7 minutes per side until cooked through (165°F internal).",
      "Let chicken rest 5 minutes, then slice into strips.",
      "Warm tortillas in a dry pan or microwave for 20 seconds.",
      "Toss romaine with Caesar dressing in a large bowl.",
      "Layer chicken, dressed romaine, parmesan, and croutons on each tortilla.",
      "Roll tightly, tucking in the sides as you go.",
      "Slice in half on the diagonal and serve.",
    ],
    tips: [
      "Rest the chicken after cooking to keep it juicy.",
      "Warm tortillas are easier to fold without cracking.",
      "Add avocado slices for extra richness.",
    ],
  },
  {
    id: "spaghetti-bolognese",
    name: "Classic Spaghetti Bolognese",
    description: "Rich, slow-cooked meat sauce with spaghetti, finished with fresh parmesan.",
    category: "Dinner",
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    calories: 620,
    rating: 4.9,
    emoji: "🍝",
    tags: ["Italian", "comfort food", "family-friendly"],
    ingredients: [
      { amount: "400g", item: "spaghetti" },
      { amount: "500g", item: "ground beef" },
      { amount: "1 large", item: "onion, finely diced" },
      { amount: "3 cloves", item: "garlic, minced" },
      { amount: "2 stalks", item: "celery, finely diced" },
      { amount: "2 medium", item: "carrots, finely diced" },
      { amount: "400g can", item: "crushed tomatoes" },
      { amount: "2 tbsp", item: "tomato paste" },
      { amount: "½ cup", item: "red wine" },
      { amount: "1 cup", item: "beef stock" },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "to serve", item: "parmesan and fresh basil" },
    ],
    steps: [
      "Heat olive oil in a large heavy-bottomed pot over medium heat.",
      "Sauté onion, celery, and carrots for 8–10 minutes until softened.",
      "Add garlic and cook 1 minute until fragrant.",
      "Increase heat to high, add ground beef, and cook breaking up lumps until browned.",
      "Stir in tomato paste and cook 2 minutes.",
      "Pour in wine and let it bubble for 2 minutes.",
      "Add crushed tomatoes and beef stock. Stir well and bring to a simmer.",
      "Reduce heat to low, cover, and simmer 45 minutes, stirring occasionally.",
      "Cook spaghetti al dente according to package directions.",
      "Toss pasta with sauce and serve topped with parmesan and basil.",
    ],
    tips: [
      "The soffritto (onion, celery, carrot) is the flavor base — don't rush it.",
      "A splash of whole milk near the end gives a silkier sauce.",
      "Bolognese gets better the next day as flavors meld.",
    ],
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Tender chicken in a velvety, spiced tomato-cream sauce. A beloved Indian classic.",
    category: "Dinner",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    calories: 540,
    rating: 4.9,
    emoji: "🍛",
    tags: ["Indian", "creamy", "spiced"],
    ingredients: [
      { amount: "700g", item: "chicken thighs, cubed" },
      { amount: "1 cup", item: "plain yogurt" },
      { amount: "2 tsp", item: "garam masala" },
      { amount: "2 tsp", item: "ground cumin" },
      { amount: "1 tsp", item: "turmeric" },
      { amount: "1 tsp", item: "chili powder" },
      { amount: "3 cloves", item: "garlic, minced" },
      { amount: "1 tbsp", item: "fresh ginger, grated" },
      { amount: "400g can", item: "crushed tomatoes" },
      { amount: "1 cup", item: "heavy cream" },
      { amount: "3 tbsp", item: "butter" },
      { amount: "to serve", item: "basmati rice and naan bread" },
    ],
    steps: [
      "Mix chicken with yogurt, half the spices, half the garlic, and ginger. Marinate 1+ hours.",
      "Cook marinated chicken in a hot pan until charred slightly. Set aside.",
      "Melt butter in the same pan, add remaining garlic and ginger, cook 1 minute.",
      "Add remaining spices, stir 30 seconds until fragrant.",
      "Pour in crushed tomatoes and simmer 15 minutes.",
      "Blend the sauce until smooth using an immersion blender.",
      "Return to heat, stir in heavy cream, and simmer 5 minutes.",
      "Add the cooked chicken back to the sauce. Simmer 10 minutes.",
      "Adjust seasoning and serve over basmati rice with naan.",
    ],
    tips: [
      "Marinating overnight gives the most flavor and tender chicken.",
      "Blend the sauce for that restaurant-smooth texture.",
      "Add a pinch of sugar if the sauce tastes too acidic.",
    ],
  },
  {
    id: "salmon-teriyaki",
    name: "Teriyaki Salmon",
    description: "Glazed salmon fillets with a sweet-savory homemade teriyaki sauce and steamed jasmine rice.",
    category: "Dinner",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 480,
    rating: 4.7,
    emoji: "🍣",
    tags: ["Japanese", "healthy", "quick", "seafood"],
    ingredients: [
      { amount: "2 fillets", item: "salmon (200g each)" },
      { amount: "3 tbsp", item: "soy sauce" },
      { amount: "2 tbsp", item: "mirin" },
      { amount: "1 tbsp", item: "honey" },
      { amount: "1 tsp", item: "sesame oil" },
      { amount: "1 clove", item: "garlic, minced" },
      { amount: "1 tsp", item: "fresh ginger, grated" },
      { amount: "1 tsp", item: "cornstarch + 1 tbsp water" },
      { amount: "to serve", item: "jasmine rice, sesame seeds, green onion" },
    ],
    steps: [
      "Whisk soy sauce, mirin, honey, sesame oil, garlic, and ginger in a small bowl.",
      "Pour half over salmon fillets and marinate 15 minutes.",
      "Heat remaining marinade in a small saucepan over medium heat.",
      "Add cornstarch mixture and stir until thickened, about 2 minutes. Set aside.",
      "Heat a non-stick pan over medium-high heat. Cook salmon skin-side up 4 minutes.",
      "Flip and cook 3–4 more minutes until cooked through.",
      "Brush with the thickened teriyaki glaze and cook 1 more minute.",
      "Serve over jasmine rice, garnished with sesame seeds and sliced green onion.",
    ],
    tips: [
      "Don't overcook salmon — it should be slightly pink in the center.",
      "Pat salmon dry before cooking for a better sear.",
      "Double the sauce recipe and keep extra in the fridge for 1 week.",
    ],
  },
  {
    id: "chocolate-lava-cake",
    name: "Chocolate Lava Cake",
    description: "Warm, fudgy chocolate cakes with a molten center — the ultimate indulgent dessert.",
    category: "Dessert",
    difficulty: "Medium",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    calories: 420,
    rating: 5.0,
    emoji: "🍫",
    tags: ["chocolate", "indulgent", "impressive"],
    ingredients: [
      { amount: "200g", item: "dark chocolate (70%), chopped" },
      { amount: "100g", item: "unsalted butter" },
      { amount: "3 large", item: "eggs" },
      { amount: "3", item: "egg yolks" },
      { amount: "100g", item: "powdered sugar" },
      { amount: "60g", item: "all-purpose flour" },
      { amount: "pinch", item: "salt" },
      { amount: "to serve", item: "vanilla ice cream and powdered sugar" },
    ],
    steps: [
      "Preheat oven to 220°C (425°F). Butter and flour 4 ramekins.",
      "Melt chocolate and butter together over a double boiler or in the microwave in 30-sec bursts.",
      "Stir until smooth, then let cool slightly.",
      "Whisk eggs, yolks, and powdered sugar until thick and pale, about 2 minutes.",
      "Fold the chocolate mixture into the egg mixture.",
      "Fold in flour and salt until just combined.",
      "Pour batter into prepared ramekins. Refrigerate at least 30 minutes (or up to 24 hours).",
      "Bake 10–12 minutes until edges are set but center is still jiggly.",
      "Let rest 1 minute, then invert onto plates. Dust with powdered sugar and serve with ice cream.",
    ],
    tips: [
      "The exact bake time depends on your oven — test with one cake first.",
      "Refrigerating the batter makes the gooey center easier to control.",
      "Use high-quality chocolate for the best flavor.",
    ],
  },
  {
    id: "tiramisu",
    name: "Classic Tiramisu",
    description: "Layers of espresso-soaked ladyfingers and creamy mascarpone — Italy's most iconic dessert.",
    category: "Dessert",
    difficulty: "Medium",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    calories: 380,
    rating: 4.8,
    emoji: "☕",
    tags: ["Italian", "no-bake", "coffee", "make-ahead"],
    ingredients: [
      { amount: "500g", item: "mascarpone cheese" },
      { amount: "4 large", item: "eggs, separated" },
      { amount: "100g", item: "caster sugar" },
      { amount: "300ml", item: "strong espresso, cooled" },
      { amount: "3 tbsp", item: "Marsala wine or coffee liqueur" },
      { amount: "200g", item: "ladyfinger biscuits (savoiardi)" },
      { amount: "to dust", item: "good quality cocoa powder" },
    ],
    steps: [
      "Beat egg yolks and sugar together until thick and pale.",
      "Fold mascarpone into the egg yolk mixture until smooth.",
      "Whip egg whites to stiff peaks in a clean bowl.",
      "Gently fold egg whites into mascarpone mixture in three batches.",
      "Mix cooled espresso with Marsala wine in a shallow dish.",
      "Quickly dip each ladyfinger into the espresso (1–2 seconds each side).",
      "Arrange a layer of soaked ladyfingers in a 9x13 inch dish.",
      "Spread half the mascarpone cream over the top.",
      "Repeat with another layer of ladyfingers and remaining cream.",
      "Dust generously with cocoa powder. Refrigerate at least 4 hours.",
    ],
    tips: [
      "Do not over-soak the ladyfingers — a quick dip is all they need.",
      "Tiramisu is even better made the day before.",
      "Use freshly brewed espresso for the best coffee flavor.",
    ],
  },
  {
    id: "mango-smoothie",
    name: "Tropical Mango Smoothie",
    description: "A thick, creamy blend of mango, pineapple, and coconut milk for instant sunshine in a glass.",
    category: "Drinks",
    difficulty: "Easy",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    calories: 210,
    rating: 4.6,
    emoji: "🥭",
    tags: ["vegan", "healthy", "tropical", "no-cook"],
    ingredients: [
      { amount: "2 cups", item: "frozen mango chunks" },
      { amount: "1 cup", item: "frozen pineapple chunks" },
      { amount: "1 cup", item: "coconut milk" },
      { amount: "½ cup", item: "orange juice" },
      { amount: "1 tbsp", item: "honey or agave (optional)" },
      { amount: "1 tsp", item: "fresh lime juice" },
      { amount: "to garnish", item: "fresh mango slice and mint" },
    ],
    steps: [
      "Add coconut milk and orange juice to the blender first.",
      "Add frozen mango and pineapple chunks.",
      "Blend on high for 60 seconds until completely smooth.",
      "Add honey and lime juice. Blend briefly to combine.",
      "Taste and adjust sweetness.",
      "Pour into chilled glasses and garnish with a mango slice and fresh mint.",
    ],
    tips: [
      "Frozen fruit gives a thicker, colder smoothie without watering it down with ice.",
      "For a protein boost, add a scoop of vanilla protein powder.",
      "Use full-fat coconut milk for a creamier result.",
    ],
  },
  {
    id: "guacamole",
    name: "Fresh Guacamole",
    description: "Chunky, vibrant guacamole with lime, jalapeño, and cilantro. Ready in 10 minutes.",
    category: "Snack",
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 150,
    rating: 4.8,
    emoji: "🫑",
    tags: ["vegan", "Mexican", "no-cook", "healthy"],
    ingredients: [
      { amount: "3 ripe", item: "avocados" },
      { amount: "1", item: "lime, juiced" },
      { amount: "½ small", item: "red onion, finely diced" },
      { amount: "1–2", item: "jalapeños, seeded and minced" },
      { amount: "2 cloves", item: "garlic, minced" },
      { amount: "½ cup", item: "fresh cilantro, chopped" },
      { amount: "2 medium", item: "Roma tomatoes, diced" },
      { amount: "1 tsp", item: "cumin" },
      { amount: "to taste", item: "salt and black pepper" },
    ],
    steps: [
      "Halve and pit the avocados. Scoop flesh into a bowl.",
      "Add lime juice and mash with a fork to desired chunkiness.",
      "Stir in diced red onion, jalapeño, and garlic.",
      "Fold in diced tomatoes and chopped cilantro.",
      "Season with cumin, salt, and pepper.",
      "Taste and adjust seasoning — it may need more lime or salt.",
      "Press plastic wrap directly onto the surface and refrigerate until serving.",
      "Serve with tortilla chips or vegetable sticks.",
    ],
    tips: [
      "Add the lime juice immediately to slow browning.",
      "Press plastic wrap directly onto the surface to keep it green.",
      "Make it chunkier or smoother based on personal preference.",
    ],
  },
  {
    id: "energy-balls",
    name: "Peanut Butter Energy Balls",
    description: "No-bake oat and peanut butter balls packed with protein, perfect for a quick energy boost.",
    category: "Snack",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 0,
    servings: 20,
    calories: 95,
    rating: 4.5,
    emoji: "🍡",
    tags: ["vegan", "no-bake", "healthy", "meal-prep"],
    ingredients: [
      { amount: "1 cup", item: "rolled oats" },
      { amount: "½ cup", item: "peanut butter" },
      { amount: "⅓ cup", item: "honey" },
      { amount: "½ cup", item: "ground flaxseed" },
      { amount: "½ cup", item: "dark chocolate chips" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "pinch", item: "salt" },
    ],
    steps: [
      "Combine all ingredients in a large mixing bowl.",
      "Stir until everything is evenly mixed.",
      "Refrigerate the mixture for 30 minutes until firm enough to roll.",
      "Roll into 1-inch balls using your hands.",
      "Place on a parchment-lined tray.",
      "Refrigerate for another 30 minutes before serving.",
      "Store in an airtight container in the fridge for up to 1 week.",
    ],
    tips: [
      "Wet your hands slightly to prevent sticking while rolling.",
      "Add shredded coconut, chia seeds, or dried fruit for variety.",
      "Freeze for up to 3 months for long-term storage.",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function getRecipesByCategory(category: Category): Recipe[] {
  return recipes.filter((r) => r.category === category);
}

export function searchRecipes(query: string): Recipe[] {
  const q = query.toLowerCase();
  return recipes.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.toLowerCase().includes(q)) ||
      r.category.toLowerCase().includes(q) ||
      r.ingredients.some((i) => i.item.toLowerCase().includes(q))
  );
}

export const categories: Category[] = ["Breakfast", "Lunch", "Dinner", "Dessert", "Snack", "Drinks"];

export const categoryEmojis: Record<Category, string> = {
  Breakfast: "🌅",
  Lunch: "☀️",
  Dinner: "🌙",
  Dessert: "🍰",
  Snack: "🥨",
  Drinks: "🥤",
};
