import { Category, Todo } from "./types";

export const defaultCategories: Category[] = [
  { id: "work", name: "Work", color: "#6366f1", icon: "💼" },
  { id: "personal", name: "Personal", color: "#f59e0b", icon: "🏠" },
  { id: "health", name: "Health", color: "#10b981", icon: "🏃" },
  { id: "learning", name: "Learning", color: "#3b82f6", icon: "📚" },
  { id: "shopping", name: "Shopping", color: "#ec4899", icon: "🛒" },
];

export const sampleTodos: Todo[] = [
  {
    id: "1",
    title: "Finish quarterly report",
    description: "Compile Q1 metrics and present to stakeholders",
    priority: "high",
    status: "active",
    categoryId: "work",
    createdAt: "2026-05-01T09:00:00Z",
    dueDate: "2026-05-10T17:00:00Z",
    tags: ["report", "q1"],
  },
  {
    id: "2",
    title: "Team standup preparation",
    description: "Prepare talking points for Monday's all-hands",
    priority: "medium",
    status: "completed",
    categoryId: "work",
    createdAt: "2026-05-02T08:30:00Z",
    dueDate: "2026-05-05T09:00:00Z",
    completedAt: "2026-05-04T22:00:00Z",
    tags: ["meeting"],
  },
  {
    id: "3",
    title: "Morning run",
    description: "5km at Riverside Park",
    priority: "medium",
    status: "active",
    categoryId: "health",
    createdAt: "2026-05-03T07:00:00Z",
    dueDate: "2026-05-08T08:00:00Z",
    tags: ["exercise", "outdoor"],
  },
  {
    id: "4",
    title: "Read 'Atomic Habits'",
    description: "Finish chapters 7–12 this week",
    priority: "low",
    status: "active",
    categoryId: "learning",
    createdAt: "2026-05-01T20:00:00Z",
    dueDate: "2026-05-14T23:59:00Z",
    tags: ["reading", "self-improvement"],
  },
  {
    id: "5",
    title: "Grocery shopping",
    description: "Milk, eggs, bread, vegetables, fruits",
    priority: "medium",
    status: "completed",
    categoryId: "shopping",
    createdAt: "2026-05-04T10:00:00Z",
    completedAt: "2026-05-04T11:30:00Z",
    tags: ["weekly", "essentials"],
  },
  {
    id: "6",
    title: "Call mom",
    description: "Sunday afternoon check-in",
    priority: "high",
    status: "completed",
    categoryId: "personal",
    createdAt: "2026-05-05T12:00:00Z",
    completedAt: "2026-05-05T14:00:00Z",
    tags: ["family"],
  },
  {
    id: "7",
    title: "Complete TypeScript course",
    description: "Advanced generics and utility types section",
    priority: "high",
    status: "active",
    categoryId: "learning",
    createdAt: "2026-05-06T09:00:00Z",
    dueDate: "2026-05-15T23:59:00Z",
    tags: ["typescript", "coding"],
  },
  {
    id: "8",
    title: "Dentist appointment",
    description: "Annual checkup at City Dental Clinic",
    priority: "high",
    status: "active",
    categoryId: "health",
    createdAt: "2026-05-07T08:00:00Z",
    dueDate: "2026-05-12T10:00:00Z",
    tags: ["appointment"],
  },
  {
    id: "9",
    title: "Buy birthday gift for Alex",
    description: "Check wishlist on Instagram",
    priority: "medium",
    status: "active",
    categoryId: "shopping",
    createdAt: "2026-05-07T16:00:00Z",
    dueDate: "2026-05-20T23:59:00Z",
    tags: ["birthday", "gift"],
  },
  {
    id: "10",
    title: "Plan weekend hiking trip",
    description: "Book trail permit and pack gear",
    priority: "low",
    status: "active",
    categoryId: "personal",
    createdAt: "2026-05-08T10:00:00Z",
    dueDate: "2026-05-22T23:59:00Z",
    tags: ["outdoor", "weekend"],
  },
];
