export type Category = "Breakfast" | "Lunch" | "Dinner" | "Dessert" | "Snack" | "Drink";

export interface Recipe {
  id: string;
  title: string;
  category: Category;
  cuisine: string;
  time: number; // minutes
  servings: number;
  difficulty: "Easy" | "Medium" | "Hard";
  description: string;
  image: string;
  tags: string[];
  ingredients: { amount: string; item: string }[];
  steps: string[];
  calories: number;
}

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Avocado Toast with Poached Eggs",
    category: "Breakfast",
    cuisine: "American",
    time: 15,
    servings: 2,
    difficulty: "Easy",
    description: "Creamy smashed avocado on crispy sourdough topped with perfectly poached eggs and a sprinkle of chili flakes.",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800&q=80",
    tags: ["healthy", "vegetarian", "quick"],
    calories: 320,
    ingredients: [
      { amount: "2 slices", item: "sourdough bread" },
      { amount: "1 large", item: "ripe avocado" },
      { amount: "2", item: "eggs" },
      { amount: "1 tbsp", item: "white vinegar" },
      { amount: "1/2 tsp", item: "chili flakes" },
      { amount: "1 tbsp", item: "lemon juice" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Toast sourdough until golden and crispy.",
      "Halve and pit the avocado. Scoop flesh into a bowl, add lemon juice, salt, and pepper. Smash to desired consistency.",
      "Bring a saucepan of water to a gentle simmer. Add white vinegar.",
      "Crack each egg into a small bowl. Create a gentle whirlpool in the water and slide eggs in. Cook 3–4 minutes.",
      "Spread avocado mixture on toast. Top with a poached egg.",
      "Finish with chili flakes and a pinch of salt.",
    ],
  },
  {
    id: "2",
    title: "Classic Spaghetti Carbonara",
    category: "Dinner",
    cuisine: "Italian",
    time: 25,
    servings: 4,
    difficulty: "Medium",
    description: "An authentic Roman pasta dish made with eggs, hard cheese, cured pork, and pepper — no cream needed.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80",
    tags: ["pasta", "italian", "comfort-food"],
    calories: 520,
    ingredients: [
      { amount: "400g", item: "spaghetti" },
      { amount: "200g", item: "guanciale or pancetta" },
      { amount: "4", item: "egg yolks" },
      { amount: "1 whole", item: "egg" },
      { amount: "100g", item: "Pecorino Romano, grated" },
      { amount: "50g", item: "Parmesan, grated" },
      { amount: "2 tsp", item: "black pepper, coarsely ground" },
      { amount: "to taste", item: "salt" },
    ],
    steps: [
      "Cook spaghetti in salted boiling water until al dente. Reserve 1 cup pasta water.",
      "Cook guanciale in a pan over medium heat until crispy. Remove from heat.",
      "Whisk egg yolks, whole egg, Pecorino, and Parmesan together with plenty of black pepper.",
      "Drain pasta and add to the pan with guanciale off the heat.",
      "Add egg mixture and toss vigorously, adding pasta water a little at a time to create a silky sauce.",
      "Serve immediately with extra cheese and pepper.",
    ],
  },
  {
    id: "3",
    title: "Mango Lassi",
    category: "Drink",
    cuisine: "Indian",
    time: 5,
    servings: 2,
    difficulty: "Easy",
    description: "A refreshing Indian yogurt drink blended with ripe mango, a touch of cardamom, and honey.",
    image: "https://images.unsplash.com/photo-1527861153539-6f067c5d0c04?w=800&q=80",
    tags: ["vegan-adaptable", "refreshing", "quick"],
    calories: 185,
    ingredients: [
      { amount: "2 cups", item: "ripe mango chunks (fresh or frozen)" },
      { amount: "1 cup", item: "plain yogurt" },
      { amount: "1/2 cup", item: "milk" },
      { amount: "2 tbsp", item: "honey" },
      { amount: "1/4 tsp", item: "ground cardamom" },
      { amount: "1 cup", item: "ice cubes" },
    ],
    steps: [
      "Combine mango, yogurt, milk, honey, and cardamom in a blender.",
      "Add ice cubes.",
      "Blend until completely smooth and frothy.",
      "Taste and adjust sweetness if needed.",
      "Pour into tall glasses and serve immediately.",
    ],
  },
  {
    id: "4",
    title: "Chicken Tikka Masala",
    category: "Dinner",
    cuisine: "Indian",
    time: 50,
    servings: 4,
    difficulty: "Medium",
    description: "Tender marinated chicken in a rich, smoky tomato-cream sauce. A beloved curry that's deeply flavorful.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    tags: ["curry", "indian", "comfort-food"],
    calories: 450,
    ingredients: [
      { amount: "700g", item: "chicken breast, cubed" },
      { amount: "1 cup", item: "plain yogurt" },
      { amount: "2 tbsp", item: "tikka masala spice blend" },
      { amount: "400g", item: "crushed tomatoes" },
      { amount: "1 cup", item: "heavy cream" },
      { amount: "2", item: "onions, diced" },
      { amount: "4 cloves", item: "garlic, minced" },
      { amount: "1 tbsp", item: "fresh ginger, grated" },
      { amount: "2 tbsp", item: "butter" },
      { amount: "1 tsp", item: "garam masala" },
    ],
    steps: [
      "Marinate chicken in yogurt and half the spice blend for at least 30 minutes.",
      "Grill or broil chicken until slightly charred. Set aside.",
      "Sauté onions in butter until golden. Add garlic and ginger, cook 2 minutes.",
      "Add remaining spices and cook 1 minute. Add crushed tomatoes, simmer 15 minutes.",
      "Stir in cream and add the chicken. Simmer 10 minutes.",
      "Finish with garam masala. Serve with basmati rice and naan.",
    ],
  },
  {
    id: "5",
    title: "Chocolate Lava Cake",
    category: "Dessert",
    cuisine: "French",
    time: 20,
    servings: 4,
    difficulty: "Medium",
    description: "Decadent individual chocolate cakes with a molten liquid center. Impressive yet surprisingly simple.",
    image: "https://images.unsplash.com/photo-1617305855058-336d24456869?w=800&q=80",
    tags: ["chocolate", "dessert", "dinner-party"],
    calories: 390,
    ingredients: [
      { amount: "200g", item: "dark chocolate (70%)" },
      { amount: "100g", item: "unsalted butter" },
      { amount: "4", item: "eggs" },
      { amount: "4", item: "egg yolks" },
      { amount: "100g", item: "caster sugar" },
      { amount: "50g", item: "all-purpose flour" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "pinch", item: "salt" },
    ],
    steps: [
      "Preheat oven to 200°C. Butter and flour 4 ramekins.",
      "Melt chocolate and butter together until smooth.",
      "Whisk eggs, yolks, and sugar until thick and pale.",
      "Fold chocolate mixture into eggs. Sift in flour and fold gently.",
      "Pour into ramekins. Bake 10–12 minutes until edges are set but center jiggles.",
      "Rest 1 minute. Invert onto plates and serve with vanilla ice cream.",
    ],
  },
  {
    id: "6",
    title: "Greek Salad",
    category: "Lunch",
    cuisine: "Greek",
    time: 10,
    servings: 4,
    difficulty: "Easy",
    description: "A vibrant, no-cook salad of crisp cucumber, ripe tomatoes, olives, and creamy feta with herby dressing.",
    image: "https://images.unsplash.com/photo-1515516969-d4008cc6241a?w=800&q=80",
    tags: ["healthy", "vegetarian", "quick", "no-cook"],
    calories: 195,
    ingredients: [
      { amount: "4 large", item: "tomatoes, cut into wedges" },
      { amount: "1 large", item: "cucumber, sliced" },
      { amount: "1", item: "red onion, thinly sliced" },
      { amount: "200g", item: "feta cheese, cubed" },
      { amount: "100g", item: "kalamata olives" },
      { amount: "1 tsp", item: "dried oregano" },
      { amount: "4 tbsp", item: "extra virgin olive oil" },
      { amount: "2 tbsp", item: "red wine vinegar" },
    ],
    steps: [
      "Combine tomatoes, cucumber, and red onion in a large bowl.",
      "Add kalamata olives.",
      "Top with feta cheese (do not crumble — keep in large chunks).",
      "Whisk olive oil and red wine vinegar, pour over salad.",
      "Sprinkle with oregano, salt, and pepper.",
      "Serve immediately or refrigerate up to 1 hour.",
    ],
  },
  {
    id: "7",
    title: "Banana Pancakes",
    category: "Breakfast",
    cuisine: "American",
    time: 20,
    servings: 2,
    difficulty: "Easy",
    description: "Fluffy golden pancakes naturally sweetened with ripe banana, perfect for a cozy weekend morning.",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&q=80",
    tags: ["vegetarian", "breakfast", "sweet"],
    calories: 280,
    ingredients: [
      { amount: "2 ripe", item: "bananas" },
      { amount: "2", item: "eggs" },
      { amount: "1 cup", item: "all-purpose flour" },
      { amount: "1 cup", item: "milk" },
      { amount: "1 tsp", item: "baking powder" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "pinch", item: "salt" },
      { amount: "1 tbsp", item: "butter, for cooking" },
    ],
    steps: [
      "Mash bananas in a large bowl until smooth.",
      "Whisk in eggs, milk, and vanilla.",
      "Fold in flour, baking powder, and salt until just combined (lumps are fine).",
      "Heat a non-stick pan over medium heat. Add a little butter.",
      "Pour 1/4 cup batter per pancake. Cook until bubbles form, then flip.",
      "Cook 1–2 minutes more. Serve with maple syrup and fresh fruit.",
    ],
  },
  {
    id: "8",
    title: "Caprese Skewers",
    category: "Snack",
    cuisine: "Italian",
    time: 10,
    servings: 6,
    difficulty: "Easy",
    description: "Elegant bite-sized skewers of fresh mozzarella, cherry tomatoes, and basil drizzled with balsamic glaze.",
    image: "https://images.unsplash.com/photo-1506280754576-f6fa8a873550?w=800&q=80",
    tags: ["vegetarian", "party", "no-cook", "quick"],
    calories: 120,
    ingredients: [
      { amount: "250g", item: "fresh mozzarella balls (bocconcini)" },
      { amount: "250g", item: "cherry tomatoes" },
      { amount: "20 leaves", item: "fresh basil" },
      { amount: "3 tbsp", item: "extra virgin olive oil" },
      { amount: "2 tbsp", item: "balsamic glaze" },
      { amount: "to taste", item: "flaky sea salt and black pepper" },
    ],
    steps: [
      "Thread a cherry tomato, basil leaf (folded), and mozzarella ball onto each skewer.",
      "Arrange on a serving platter.",
      "Drizzle with olive oil and balsamic glaze.",
      "Season with flaky sea salt and cracked black pepper.",
      "Serve immediately.",
    ],
  },
  {
    id: "9",
    title: "Beef Tacos",
    category: "Dinner",
    cuisine: "Mexican",
    time: 30,
    servings: 4,
    difficulty: "Easy",
    description: "Seasoned ground beef in warm tortillas with fresh pico de gallo, sour cream, and sharp cheddar.",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
    tags: ["mexican", "quick", "family-friendly"],
    calories: 410,
    ingredients: [
      { amount: "500g", item: "ground beef" },
      { amount: "8", item: "small flour or corn tortillas" },
      { amount: "1 packet", item: "taco seasoning" },
      { amount: "1/3 cup", item: "water" },
      { amount: "1 cup", item: "shredded cheddar cheese" },
      { amount: "1/2 cup", item: "sour cream" },
      { amount: "2", item: "tomatoes, diced" },
      { amount: "1/2", item: "white onion, diced" },
      { amount: "1/4 cup", item: "cilantro, chopped" },
      { amount: "1", item: "lime, cut into wedges" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat. Drain excess fat.",
      "Add taco seasoning and water. Stir and simmer 5 minutes until thickened.",
      "Mix tomatoes, onion, cilantro, and lime juice for pico de gallo.",
      "Warm tortillas in a dry pan or microwave.",
      "Build tacos: beef, cheese, pico de gallo, sour cream.",
      "Serve with lime wedges.",
    ],
  },
  {
    id: "10",
    title: "Strawberry Cheesecake",
    category: "Dessert",
    cuisine: "American",
    time: 300,
    servings: 10,
    difficulty: "Hard",
    description: "A classic baked New York-style cheesecake with a buttery graham cracker crust and fresh strawberry topping.",
    image: "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=800&q=80",
    tags: ["dessert", "baking", "celebration"],
    calories: 480,
    ingredients: [
      { amount: "200g", item: "graham crackers, crushed" },
      { amount: "100g", item: "butter, melted" },
      { amount: "600g", item: "cream cheese, softened" },
      { amount: "200g", item: "sugar" },
      { amount: "3", item: "eggs" },
      { amount: "1 cup", item: "sour cream" },
      { amount: "2 tsp", item: "vanilla extract" },
      { amount: "300g", item: "fresh strawberries" },
      { amount: "3 tbsp", item: "strawberry jam" },
    ],
    steps: [
      "Mix graham crackers and butter. Press into a springform pan. Bake at 175°C for 10 minutes.",
      "Beat cream cheese and sugar until smooth. Add eggs one at a time.",
      "Mix in sour cream and vanilla. Pour over crust.",
      "Bake in a water bath at 160°C for 1 hour. Turn off oven, leave door ajar for 1 hour.",
      "Refrigerate overnight.",
      "Hull and halve strawberries. Warm jam and toss with strawberries. Top cheesecake.",
    ],
  },
  {
    id: "11",
    title: "Tom Yum Soup",
    category: "Lunch",
    cuisine: "Thai",
    time: 30,
    servings: 4,
    difficulty: "Medium",
    description: "A bold, tangy Thai soup bursting with lemongrass, kaffir lime, galangal, and plump shrimp.",
    image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80",
    tags: ["soup", "thai", "spicy"],
    calories: 190,
    ingredients: [
      { amount: "1L", item: "chicken broth" },
      { amount: "300g", item: "shrimp, peeled and deveined" },
      { amount: "2 stalks", item: "lemongrass, bruised and chopped" },
      { amount: "4 leaves", item: "kaffir lime leaves" },
      { amount: "3 slices", item: "galangal" },
      { amount: "200g", item: "mushrooms, sliced" },
      { amount: "3 tbsp", item: "fish sauce" },
      { amount: "2 tbsp", item: "lime juice" },
      { amount: "2 tbsp", item: "Thai chili paste (nam prik pao)" },
      { amount: "2", item: "Thai chilies, sliced" },
    ],
    steps: [
      "Bring broth to a boil. Add lemongrass, galangal, and lime leaves. Simmer 5 minutes.",
      "Add chili paste and mushrooms. Cook 3 minutes.",
      "Add shrimp, cook until pink, about 2 minutes.",
      "Season with fish sauce and lime juice.",
      "Add chilies. Taste and adjust seasoning — should be hot, sour, savory.",
      "Garnish with cilantro. Serve with jasmine rice.",
    ],
  },
  {
    id: "12",
    title: "Overnight Oats",
    category: "Breakfast",
    cuisine: "American",
    time: 5,
    servings: 1,
    difficulty: "Easy",
    description: "Creamy no-cook oats soaked overnight with chia seeds, topped with fresh berries and honey.",
    image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800&q=80",
    tags: ["healthy", "vegan", "quick", "meal-prep"],
    calories: 340,
    ingredients: [
      { amount: "1/2 cup", item: "rolled oats" },
      { amount: "1 tbsp", item: "chia seeds" },
      { amount: "3/4 cup", item: "milk (any type)" },
      { amount: "1/4 cup", item: "Greek yogurt" },
      { amount: "1 tbsp", item: "honey or maple syrup" },
      { amount: "1/2 tsp", item: "vanilla extract" },
      { amount: "1/2 cup", item: "fresh berries, to top" },
    ],
    steps: [
      "Combine oats, chia seeds, milk, yogurt, sweetener, and vanilla in a jar.",
      "Stir well to combine.",
      "Cover and refrigerate overnight (minimum 6 hours).",
      "In the morning, stir. Add a splash of milk if too thick.",
      "Top with fresh berries and a drizzle of honey.",
    ],
  },
];

export const categories: Category[] = ["Breakfast", "Lunch", "Dinner", "Dessert", "Snack", "Drink"];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function searchRecipes(query: string, category?: Category): Recipe[] {
  const q = query.toLowerCase().trim();
  return recipes.filter((r) => {
    const matchesCategory = !category || r.category === category;
    if (!q) return matchesCategory;
    const matchesQuery =
      r.title.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.cuisine.toLowerCase().includes(q) ||
      r.tags.some((t) => t.includes(q)) ||
      r.ingredients.some((i) => i.item.toLowerCase().includes(q));
    return matchesCategory && matchesQuery;
  });
}
